// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/agilistikmal/media-wall-go/internal/mediawall/delivery/rest"
	"github.com/agilistikmal/media-wall-go/internal/mediawall/delivery/rest/route"
	"github.com/agilistikmal/media-wall-go/internal/mediawall/service"
)

// Injectors from injector.go:

func InjectRoute() *route.Route {
	tikTokService := service.NewTikTokService()
	tikTokHandler := rest.NewTikTokHandler(tikTokService)
	routeRoute := route.NewRoutes(tikTokHandler)
	return routeRoute
}
